# clickhouse service
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    component: clickhouse
    app: clickhouse
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    component: clickhouse
    app: clickhouse

